name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Construct AppDir
      run: make
    - name: Get appimagetool
      run: |
        curl --location -o appimagetool https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage
        chmod +x appimagetool
    - name: Make AppImage
      run: ./appimagetool build/anki.AppDir
    - name: Upload AppImage
      uses: actions/upload-artifact@v1
      with:
        name: Anki-x86_64.AppImage
        path: ./Anki-x86_64.AppImage
